language: node_js
node_js:
  # Test on latest stable and lts versions
  - "lts/*"
  - "node"

# For performance:
sudo: false
git:
  depth: 1

install:
  # Run `npm ci` if appropriate and version of npm is new enough; otherwise `npm install`
  - if [ -f package-lock.json ] && [ npm ci --help 2>&1 >/dev/null ] ; then npm ci ; else npm install ; fi
